# Generated by Django 5.1.7 on 2025-06-02 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradeApp', '0010_rename_email_withdraw_request_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
