# Generated by Django 5.1.7 on 2025-09-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeApp', '0011_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='available',
            field=models.CharField(default='0.00', max_length=200),
        ),
        migrations.AddField(
            model_name='wallet',
            name='locked',
            field=models.CharField(default='0.00', max_length=200),
        ),
    ]
