# Generated by Django 5.1.7 on 2025-09-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeApp', '0013_trade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='locked',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
