# Generated by Django 5.1.7 on 2025-09-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeApp', '0014_alter_wallet_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='available',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
