# Generated by Django 5.1.7 on 2025-09-17 09:33

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeApp', '0015_alter_wallet_amount_alter_wallet_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trade',
            options={'ordering': ['-created_at'], 'verbose_name': 'Trade', 'verbose_name_plural': 'Trades'},
        ),
        migrations.AddField(
            model_name='trade',
            name='trade_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Trade amount in USD', max_digits=10, validators=[django.core.validators.MinValueValidator(10.0)]),
        ),
        migrations.AlterField(
            model_name='trade',
            name='coin',
            field=models.CharField(help_text='Trading pair, e.g., BTC/USDT', max_length=20),
        ),
        migrations.AlterField(
            model_name='trade',
            name='duration',
            field=models.IntegerField(help_text='Trade duration in seconds', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='trade',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='Time when trade ends', null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price at trade initiation', max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='trade',
            name='profit_percentage',
            field=models.IntegerField(help_text='Expected profit percentage', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='trade',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL),
        ),
    ]
