# Generated by Django 5.1.7 on 2025-09-17 09:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeApp', '0016_alter_trade_options_trade_trade_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36),
        ),
    ]
