# Generated by Django 5.1.7 on 2025-09-17 09:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeApp', '0017_alter_trade_trade_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True)),
                ('coin', models.CharField(help_text='Trading pair, e.g., BTC/USDT', max_length=20)),
                ('direction', models.CharField(choices=[('up', 'Buy Up'), ('down', 'Buy Down')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Trade amount in USD', max_digits=10, validators=[django.core.validators.MinValueValidator(10.0)])),
                ('price', models.DecimalField(decimal_places=2, help_text='Price at trade initiation', max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('profit_percentage', models.IntegerField(help_text='Expected profit percentage', validators=[django.core.validators.MinValueValidator(0)])),
                ('duration', models.IntegerField(help_text='Trade duration in seconds', validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, help_text='Time when trade ends', null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trade',
                'verbose_name_plural': 'Trades',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Trade',
        ),
    ]
