# Generated by Django 5.1.7 on 2025-09-17 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeApp', '0018_trades_delete_trade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=50)),
                ('direction', models.CharField(choices=[('up', 'Buy Up'), ('down', 'Buy Down')], max_length=10)),
                ('amount', models.FloatField()),
                ('profit_percentage', models.FloatField()),
                ('duration', models.IntegerField()),
                ('price', models.FloatField(default=0)),
                ('status', models.CharField(default='running', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Trades',
        ),
    ]
