# Generated by Django 5.1.7 on 2025-09-17 10:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeApp', '0019_trade_delete_trades'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='trade_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
